version: "3"
services:
  api:
    restart: always
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor/
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/uploads/:/var/www/uploads/
    networks:
      - mysql-phpmyadmin
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=project
      - MYSQL_DATABASE=telenursing
      - MYSQL_PASSWORD=project
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Bangkok
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS telenursing;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    networks:
      - mysql-phpmyadmin

  pma:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: project
    networks:
      - mysql-phpmyadmin
      
#Docker Networks
networks:
  mysql-phpmyadmin:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local


